development:
  bucket_name: tyler_development
  bucket: tyler_development
  access_key_id: AKIAIDEFW5P6AQLRXWGQ
  secret_access_key: 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

test:
  bucket_name: tyler_development
  bucket: tyler_development
  access_key_id: AKIAIDEFW5P6AQLRXWGQ
  secret_access_key: 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

production:
  bucket_name: tyler_development
  bucket: tyler_development
  access_key_id: AKIAIDEFW5P6AQLRXWGQ
  secret_access_key: 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

